from feast import FeatureStore

# Initialize the feature store pointing to the current directory
store = FeatureStore(repo_path=".")

# Fetch the features for a specific entity (recipe_id)
# Note: monotonically_increasing_id() assigns large integers based on data partitions.
# Try 0 first. If the output returns None values, you will need to check your 
# Parquet file to grab a valid ID generated by your specific Spark partition structure.
features = store.get_online_features(
    features=[
        "recipe_features:title",
        "recipe_features:ingredients",
        "recipe_features:directions",
        "recipe_features:source"
    ],
    entity_rows=[
        {"recipe_id": 0} 
    ]
).to_df()

# Print the retrieved dataframe
print(features.to_string())