FROM fedora:40

RUN dnf update -y && \
    dnf install -y \
    git \
    curl \
    wget \
    nano \
    sudo \
    python3 \
    python3-pip \
    java-17-openjdk \
    nodejs \
    procps-ng \
    wget \
    tar \
    awscli \
    gcc \
    gcc-c++ \
    gdb \
    make \
    cmake \
    tar \
    findutils \
    which \
    grep  \
    docker && \
    dnf clean all

    ARG USERNAME=devuser
    ARG USER_UID=1000
    ARG USER_GID=$USER_UID

    RUN groupadd --gid $USER_GID $USERNAME \
        && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
        && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
        && chmod 0440 /etc/sudoers.d/$USERNAME

    ENV JAVA_HOME=/usr/lib/jvm/jre-17-openjdk

    USER ${USERNAME}
    WORKDIR /workspace